"""The morning briefing: one email each weekday at 9:45 am (requested 2026-10-07).

What it reports, and how honestly:

1. **The market's trend:** SPY over the last day, week and month, and the share of S&P 500
   stocks above their 50- and 200-day averages.
2. **Top movers:** the S&P 500's biggest gainers over the last completed day, week (5
   trading days) and month (21), each with its trend. These are facts about what already
   happened, not predictions. At 9:45 am the market has been open 15 minutes, so "day"
   means the last *completed* session.
3. **History check:** what usually followed moves like these (base rates from the
   S&P 500's own history, context/research/base_rates.json). The mobile-trading-app study
   (Liu et al. 2025) found that easy access raised trend-chasing; this is the counterweight.
4. **The twins' lists (experimental):** the stocks that pass the Growth and Value Screens
   today. Neither rule beat the market in the 2011-2026 backtest, and the email says so
   every time. They are shown to be watched, never as advice. Lists are never padded.
5. **The scoreboard:** how many sealed calls are waiting and how many have been graded.

Plain code writes every number; nothing here is generated by an AI.
"""
from __future__ import annotations

import html
import json
from dataclasses import dataclass, field
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Any
from zoneinfo import ZoneInfo

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "data" / "briefings"
NY = ZoneInfo("America/New_York")
HORIZONS = {"day": 1, "week": 5, "month": 21}
TOP_N = 10
BACKTEST = ROOT / "context" / "research" / "backtests" / "2026-10-07-screens-v1" / "summary.json"


def completed_sessions(df: pd.DataFrame, now: datetime) -> pd.DataFrame:
    """Drop today's bar while the market is still open (before 4:15 pm New York time)."""
    if df.empty:
        return df
    today = pd.Timestamp(now.astimezone(NY).date())
    still_open = now.astimezone(NY).time() < datetime.strptime("16:15", "%H:%M").time()
    return df.iloc[:-1] if df.index[-1] == today and still_open else df


def trend_row(symbol: str, df: pd.DataFrame) -> dict[str, Any] | None:
    """Returns over each horizon (total return) and where the price sits vs its averages."""
    adj, close = df["AdjClose"].dropna(), df["Close"].dropna()
    if len(adj) < 22:
        return None
    row: dict[str, Any] = {"symbol": symbol, "last": float(close.iloc[-1]), "as_of": adj.index[-1]}
    for name, n in HORIZONS.items():
        row[name] = float(adj.iloc[-1] / adj.iloc[-1 - n] - 1)
    row["above_50d"] = bool(close.iloc[-1] > close.iloc[-50:].mean()) if len(close) >= 50 else None
    row["above_200d"] = bool(close.iloc[-1] > close.iloc[-200:].mean()) if len(close) >= 200 else None
    return row


def trend_label(r: dict[str, Any]) -> str:
    a50, a200 = r.get("above_50d"), r.get("above_200d")
    if a50 is None or a200 is None:
        return "short history"
    if a50 and a200:
        return "uptrend (above 50- and 200-day averages)"
    if not a50 and not a200:
        return "downtrend (below both averages)"
    return "mixed (above the 200-day, below the 50-day)" if a200 else "mixed (above the 50-day, below the 200-day)"


@dataclass
class Briefing:
    as_of: str
    market: dict[str, Any]
    movers: dict[str, list[dict[str, Any]]]
    history_note: str | None
    twins: dict[str, dict[str, Any]]
    scoreboard: list[dict[str, Any]]
    notes: list[str] = field(default_factory=list)


def build(prices: dict[str, pd.DataFrame], now: datetime | None = None,
          snapshot: pd.DataFrame | None = None, rates: dict[str, Any] | None = None,
          backtest: dict[str, Any] | None = None, scoreboard: list[dict[str, Any]] | None = None,
          names: dict[str, str] | None = None,
          headlines: dict[str, dict[str, str]] | None = None,
          filings: dict[str, list[dict[str, str]]] | None = None) -> Briefing:
    """Everything the email says, from data passed in (so it can be tested offline).
    `prices`: symbol -> Close/AdjClose/Splits, including SPY. `snapshot`: today's screen
    inputs (pit_data.live_snapshot), or None to skip the twins' lists."""
    from backend.analysis import base_rates, screens

    now = now or datetime.now(NY)
    rows = []
    for sym, df in prices.items():
        r = trend_row(sym, completed_sessions(df, now))
        if r is not None:
            rows.append(r)
    table = pd.DataFrame(rows).set_index("symbol")
    spy = table.loc["SPY"] if "SPY" in table.index else None
    stocks = table.drop(index="SPY", errors="ignore")
    as_of = (spy["as_of"] if spy is not None else stocks["as_of"].max()).strftime("%Y-%m-%d")
    stocks = stocks[stocks["as_of"].dt.strftime("%Y-%m-%d") == as_of]     # same session for all
    market = {"spy": {h: float(spy[h]) for h in HORIZONS} if spy is not None else None,
              "n_stocks": int(len(stocks)),
              "above_50d": float(stocks["above_50d"].dropna().astype(float).mean()) if len(stocks) else None,
              "above_200d": float(stocks["above_200d"].dropna().astype(float).mean()) if len(stocks) else None}
    names = names or {}
    movers = {}
    for h in HORIZONS:
        top = stocks.sort_values(h, ascending=False).head(TOP_N)
        movers[h] = [{"symbol": s, "name": names.get(s, ""), "return": float(r[h]), "last": float(r["last"]),
                      "trend": trend_label(r), "headline": (headlines or {}).get(s),
                      "filings": (filings or {}).get(s, [])}
                     for s, r in top.iterrows()]

    history_note = None
    rates = rates if rates is not None else base_rates.load()
    if rates and movers["month"]:
        row = base_rates.for_move(movers["month"][0]["return"], "1m", rates)
        if row:
            history_note = (
                f"The month's top gainer rose {movers['month'][0]['return']:.0%}. Of S&P 500 stocks "
                f"that {row['bucket']} in a month ({row['n']:,} cases since 2011), "
                f"{row['beat_spy_next_12m']:.0%} beat the S&P 500 over the next 12 months, compared "
                f"with {row['same_months_all_stocks']:.0%} of all stocks in those same months "
                f"(t = {row['vs_all_stocks_t']:+.1f}, so no reliable difference). A big move by "
                f"itself hasn't predicted the next year.")

    twins: dict[str, dict[str, Any]] = {}
    backtest = backtest if backtest is not None else _load_json(BACKTEST)
    if snapshot is not None and len(snapshot):
        g = screens.add_ratios(snapshot[snapshot["missing"] == ""])
        for version, sort_col, label in (("growth-v1", "rev_growth", "revenue growth"),
                                         ("value-v1", "ep", "earnings yield")):
            picked = g[screens.SCREENS[version](g, screens.RULES[version])].sort_values(sort_col, ascending=False)
            res = (backtest or {}).get("results", {}).get(version, {})
            twins[version] = {
                "n_passed": int(len(picked)), "n_screened": int(len(g)), "sorted_by": label,
                "picks": [{"symbol": r["ticker"], "value": float(r[sort_col])} for _, r in picked.head(TOP_N).iterrows()],
                "record": (f"{res['excess_per_year']:+.1%} a year vs the average S&P 500 stock, "
                           f"t = {res['excess_t']:+.2f}, {res['start'][:4]}–{res['end'][:4]}; "
                           f"Stage A: {res['stage_a']}") if res else "not backtested"}
    return Briefing(as_of=as_of, market=market, movers=movers, history_note=history_note,
                    twins=twins, scoreboard=scoreboard or [])


def _load_json(path: Path) -> dict[str, Any] | None:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None


# --- Rendering -----------------------------------------------------------------------

def _pct(x: float | None) -> str:
    return "n/a" if x is None or not np.isfinite(x) else f"{x:+.1%}"


def subject(b: Briefing) -> str:
    spy = (b.market.get("spy") or {}).get("day")
    return f"QuantAnalyzer morning briefing: S&P 500 {_pct(spy)} on {b.as_of}"


def to_text(b: Briefing) -> str:
    lines = [subject(b), "", "MARKET TREND"]
    spy = b.market.get("spy") or {}
    lines.append(f"S&P 500 (SPY): day {_pct(spy.get('day'))}, week {_pct(spy.get('week'))}, "
                 f"month {_pct(spy.get('month'))}")
    if b.market.get("above_200d") is not None:
        lines.append(f"{b.market['above_50d']:.0%} of {b.market['n_stocks']} S&P 500 stocks are above their "
                     f"50-day average, {b.market['above_200d']:.0%} above their 200-day.")
    for h in HORIZONS:
        lines += ["", f"TOP {TOP_N} GAINERS, LAST {h.upper()} (what happened, not a prediction)"]
        for i, m in enumerate(b.movers[h], 1):
            lines.append(f"  {i}. {m['symbol']:6s} {_pct(m['return']):>7s}  {m['trend']}")
            for f in m.get("filings") or []:
                lines.append(f"       SEC 8-K filed {f['date']}: {f['items']}")
            if m.get("headline"):
                lines.append(f"       latest headline ({m['headline']['date']}): {m['headline']['title']}")
    if b.history_note:
        lines += ["", "HISTORY CHECK", b.history_note]
    for version, t in b.twins.items():
        lines += ["", f"EXPERIMENTAL: {version} picks today ({t['n_passed']} of {t['n_screened']} passed; "
                      f"backtest: {t['record']}). Not advice."]
        lines += [f"  {p['symbol']}" for p in t["picks"]] or ["  (none passed today)"]
    lines += ["", "SCOREBOARD", *(f"  {s['agent_id']}: {s['calls']} calls, {s['graded']} graded, "
                                   f"{s['pending']} waiting" for s in b.scoreboard)]
    lines += ["", FOOTER_TEXT]
    return "\n".join(lines)


FOOTER_TEXT = ("General research and education, not personal advice. Movers are facts about the past; "
               "SEC 8-K filings are the companies' own official reports; headlines are the newest Yahoo "
               "Finance item, shown unchecked (many are clickbait); "
               "the experimental lists come from rules that did not beat the market in our own tests. "
               "Most daily moves are noise. Sources: Yahoo Finance prices, SEC filings, "
               "QuantAnalyzer backtests (context/research/ in the repo).")


def to_html(b: Briefing) -> str:
    e = html.escape
    td = 'style="padding:4px 10px;border-bottom:1px solid #e5e7eb;"'
    tdn = 'style="padding:4px 10px;border-bottom:1px solid #e5e7eb;text-align:right;font-variant-numeric:tabular-nums;"'

    def color(x: float) -> str:
        return "#15803d" if x >= 0 else "#b91c1c"

    spy = b.market.get("spy") or {}
    parts = [f'<div style="font-family:Segoe UI,Arial,sans-serif;max-width:680px;color:#111827;">',
             f'<h2 style="margin:0 0 4px;">Morning briefing</h2>',
             f'<p style="color:#6b7280;margin:0 0 16px;">Prices through the close of {e(b.as_of)}.</p>',
             '<h3 style="margin:16px 0 6px;">Market trend</h3>',
             f'<p style="margin:0;">S&amp;P 500 (SPY): day <b style="color:{color(spy.get("day", 0))}">'
             f'{_pct(spy.get("day"))}</b> · week <b>{_pct(spy.get("week"))}</b> · month <b>{_pct(spy.get("month"))}</b></p>']
    if b.market.get("above_200d") is not None:
        parts.append(f'<p style="margin:4px 0 0;">{b.market["above_50d"]:.0%} of {b.market["n_stocks"]} S&amp;P 500 '
                     f'stocks are above their 50-day average and {b.market["above_200d"]:.0%} above their 200-day.</p>')
    for h in HORIZONS:
        parts.append(f'<h3 style="margin:18px 0 4px;">Top {TOP_N} gainers, last {h}</h3>'
                     '<p style="color:#6b7280;margin:0 0 6px;font-size:13px;">What already happened, not a prediction.</p>'
                     '<table style="border-collapse:collapse;font-size:14px;">')
        for i, m in enumerate(b.movers[h], 1):
            parts.append(f'<tr><td {td}>{i}</td><td {td}><b>{e(m["symbol"])}</b> {e(m["name"])}</td>'
                         f'<td {tdn}><span style="color:{color(m["return"])}">{_pct(m["return"])}</span></td>'
                         f'<td {td}>{e(m["trend"])}</td></tr>')
            for f in m.get("filings") or []:
                parts.append(f'<tr><td></td><td colspan="3" style="padding:0 10px 4px;font-size:13px;">'
                             f'SEC 8-K filed {e(f["date"])}: <a href="{e(f["link"])}">{e(f["items"])}</a></td></tr>')
            if m.get("headline"):
                hl = m["headline"]
                parts.append(f'<tr><td></td><td colspan="3" style="padding:0 10px 6px;color:#4b5563;font-size:13px;">'
                             f'Latest headline ({e(hl["date"])}): <a href="{e(hl["link"])}">{e(hl["title"])}</a></td></tr>')
        parts.append('</table>')
    if b.history_note:
        parts.append('<div style="margin:18px 0;padding:10px 14px;background:#fef3c7;border-radius:8px;">'
                     f'<b>History check.</b> {e(b.history_note)}</div>')
    for version, t in b.twins.items():
        picks = ", ".join(e(p["symbol"]) for p in t["picks"]) or "none passed today"
        parts.append(f'<h3 style="margin:18px 0 4px;">Experimental: {e(version)} picks</h3>'
                     f'<p style="margin:0;font-size:14px;">{picks}</p>'
                     f'<p style="color:#6b7280;margin:4px 0 0;font-size:13px;">{t["n_passed"]} of {t["n_screened"]} '
                     f'stocks passed (top {TOP_N} by {e(t["sorted_by"])}). Backtest: {e(t["record"])}. '
                     f'Not advice: this rule has no proven edge.</p>')
    if b.scoreboard:
        parts.append('<h3 style="margin:18px 0 4px;">Scoreboard</h3><ul style="margin:0;padding-left:18px;">')
        parts += [f'<li>{e(s["agent_id"])}: {s["calls"]} calls sealed, {s["graded"]} graded, '
                  f'{s["pending"]} waiting</li>' for s in b.scoreboard]
        parts.append('</ul>')
    parts.append(f'<p style="color:#6b7280;font-size:12px;margin-top:22px;">{e(FOOTER_TEXT)}</p></div>')
    return "\n".join(parts)


def save(b: Briefing, out_dir: Path = OUT_DIR) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"{b.as_of}.html"
    path.write_text(to_html(b), encoding="utf-8")
    return path


def gather(progress=None) -> Briefing:
    """Live data: fresh prices for today's S&P 500, today's screen inputs, the ledger."""
    from backend import edgar, ledger
    from backend.analysis import pit_data

    members = pit_data.current_members()
    symbols = sorted({pit_data.yahoo_symbol(m)[0] for m in members if pit_data.yahoo_symbol(m)[0]} | {"SPY"})
    start = (date.today() - timedelta(days=750)).isoformat()      # covers 200-day averages and splits
    prices = pit_data.download_prices(symbols, start, progress=progress)
    snapshot = pit_data.live_snapshot(prices, completed_sessions(prices["SPY"], datetime.now(NY)).index[-1])
    try:
        names = {k.replace(".", "-"): v["title"] for k, v in edgar.ticker_map().items()}
    except edgar.EdgarError:
        names = {}
    first = build(prices, snapshot=None, scoreboard=[], names=names)
    leaders = sorted({m["symbol"] for h in ("day", "week") for m in first.movers[h][:HEADLINE_N]})
    cik_of = {pit_data.yahoo_symbol(m)[0]: m.cik for m in members if m.cik}
    since = (date.today() - timedelta(days=8)).isoformat()
    filings = {s: f for s in leaders if s in cik_of and (f := recent_8k(cik_of[s], since))}
    return build(prices, snapshot=snapshot, scoreboard=ledger.agents_summary(), names=names,
                 headlines=latest_headlines(leaders), filings=filings)


HEADLINE_N = 5           # headlines and filings for the top few movers of the day and the week

# Form 8-K items, titles as printed on the SEC's Form 8-K (sec.gov/files/form8-k.pdf).
# Companies must file an 8-K within four business days of these events, so a filing
# next to a big move is the official account of what happened.
ITEMS_8K = {
    "1.01": "Entry into a Material Definitive Agreement",
    "1.02": "Termination of a Material Definitive Agreement",
    "1.03": "Bankruptcy or Receivership",
    "1.05": "Material Cybersecurity Incidents",
    "2.01": "Completion of Acquisition or Disposition of Assets",
    "2.02": "Results of Operations and Financial Condition",
    "2.03": "Creation of a Direct Financial Obligation",
    "2.05": "Costs Associated with Exit or Disposal Activities",
    "2.06": "Material Impairments",
    "3.01": "Notice of Delisting or Failure to Satisfy a Continued Listing Rule",
    "4.02": "Non-Reliance on Previously Issued Financial Statements",
    "5.01": "Changes in Control of Registrant",
    "5.02": "Departure or Election of Directors or Certain Officers",
    "5.07": "Submission of Matters to a Vote of Security Holders",
    "7.01": "Regulation FD Disclosure",
    "8.01": "Other Events",
}


def recent_8k(cik: int, since: str) -> list[dict[str, str]]:
    """8-K filings since a date, from the SEC's own record (refreshed every few hours)."""
    from backend import edgar

    try:
        rec = edgar.submissions(cik, max_age_days=0.2).get("filings", {}).get("recent", {})
    except edgar.EdgarError:
        return []
    out = []
    for form, filed, items, accn, doc in zip(rec.get("form", []), rec.get("filingDate", []),
                                            rec.get("items", []), rec.get("accessionNumber", []),
                                            rec.get("primaryDocument", [])):
        if form in ("8-K", "8-K/A") and filed >= since:
            names = [ITEMS_8K[i] for i in (items or "").split(",") if i in ITEMS_8K]
            out.append({"date": filed, "items": "; ".join(names) or "exhibits only",
                        "link": f"https://www.sec.gov/Archives/edgar/data/{cik}/{accn.replace('-', '')}/{doc}"})
    return out


def latest_headlines(symbols: list[str], max_age_days: int = 7) -> dict[str, dict[str, str]]:
    """The newest Yahoo Finance RSS headline per symbol, if one is recent enough."""
    import time
    from curl_cffi import requests as curl_requests
    from backend.analysis import sentiment

    session = curl_requests.Session(impersonate="chrome")    # Yahoo refuses plain requests
    out = {}
    for s in symbols:
        items = [i for i in sentiment._fetch_rss_news(s, session) if i.get("providerPublishTime")]
        items = [i for i in items if time.time() - i["providerPublishTime"] < max_age_days * 86400]
        if items:
            top = max(items, key=lambda i: i["providerPublishTime"])
            out[s] = {"title": top["title"], "link": top["link"],
                      "date": datetime.fromtimestamp(top["providerPublishTime"], NY).strftime("%b %d")}
    return out
