"""Growth and Value Screen backtests on the point-in-time S&P 500 (Roadmap Phase 3).

    python scripts/run_screen_backtest.py build   # assemble the monthly panel (slow the first time)
    python scripts/run_screen_backtest.py run     # run the screens on the saved panel (seconds)

`run` writes context/research/backtests/<date>-screens-v1/ (report.md, summary.json and
one monthly CSV per screen) and records every screen version in the trials ledger.
The panel itself stays in data/cache/ (it is rebuilt from public sources by `build`).
"""
from __future__ import annotations

import json
import sys
import time
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")   # Windows consoles default to cp1252

import pandas as pd  # noqa: E402

from backend import db  # noqa: E402
from backend.analysis import pit_data, screens  # noqa: E402

PANEL = ROOT / "data" / "cache" / "screens_panel.pkl"
START = "2011-01-31"


def build() -> None:
    t0 = time.time()
    panel, cov = pit_data.build_panel(start=START, progress=lambda m: print(f"  {m}", flush=True))
    PANEL.parent.mkdir(parents=True, exist_ok=True)
    panel.to_pickle(PANEL)
    print(f"\nPanel: {len(panel)} member-months in {time.time() - t0:.0f}s")
    print(json.dumps(cov, indent=2))


def pct(x: float | None, signed: bool = False) -> str:
    if x is None or x != x:
        return "n/a"
    if signed and abs(x) < 0.001:
        return f"{x:+.2%}"                      # don't print a tiny number as "-0.0%"
    return f"{x:+.1%}" if signed else f"{x:.1%}"


def report(cov: dict, results: dict, base: dict, out: Path) -> str:
    lines = [f"# Growth and Value Screen backtest, {date.today().isoformat()}", "",
             "Generated by `scripts/run_screen_backtest.py run`. Rules: `backend/analysis/screens.py` "
             "(written before any result was seen). Data: S&P 500 members on each month-end since 2011 "
             "(point-in-time), SEC financials as first filed, Yahoo total-return prices.", "",
             "## Coverage (what the test could and couldn't see)", "",
             f"- Member-months: {cov['member_months']:,}; usable: {cov['usable']:,} "
             f"({pct(cov['usable_share'])})",
             f"- Stocks whose price series ended during a holding month (bought out or delisted; "
             f"return taken to the last price): {cov['ended_early']}",
             f"- Usable rows where a ratio was blanked as a likely filing typo (it then fails any "
             f"rule that needs it): {cov['rows_with_guarded_ratio']:,}",
             f"- Market values computed from the cover-page share count because the diluted count "
             f"was missing or mis-scaled: {cov['market_value_from_cover_count']:,}", "",
             "| Why a member-month was left out | Count |", "|---|---|"]
    lines += [f"| {k} | {v:,} |" for k, v in cov["missing_by_reason"].items()]
    for version, s in results.items():
        a = s["factor_adjusted"] or {}
        lines += ["", f"## {version}", "",
                  f"**Stage A (charters §14): {s['stage_a'].upper()}.** The bar: factor-adjusted alpha "
                  f"against the Candidate Pool with t ≥ {screens.T_BAR:.0f}, holding up in most sub-periods.", "",
                  f"- Months: {s['months']} ({s['start']} to {s['end']}); average picks "
                  f"{s['avg_picks']} out of a pool of {s['avg_pool']}; months with too few picks "
                  f"(held the pool instead): {s['thin_months']}",
                  f"- Yearly growth rate, after costs: picks {pct(s['cagr_picks_net'])}, "
                  f"Candidate Pool {pct(s['cagr_pool'])}, SPY {pct(s['cagr_spy'])}",
                  f"- Beat the pool by {pct(s['excess_per_year'], True)} a year, t = {s['excess_t']:+.2f} "
                  f"(information ratio {s['information_ratio']:+.2f}; beat it in "
                  f"{pct(s['months_beating_pool'])} of months)",
                  f"- Factor-adjusted alpha: {pct(a.get('alpha_per_year'), True)} a year, "
                  f"t = {a.get('alpha_t', float('nan')):+.2f} over {a.get('months', 0)} months "
                  f"(factor data through {a.get('factors_through', 'n/a')}); tilts: "
                  + ", ".join(f"{k} {v:+.2f}" for k, v in (a.get("betas") or {}).items()),
                  f"- Years at or above the 25% hurdle: {s['years_at_25pct']} of {s['years']}",
                  f"- Average monthly turnover: {pct(s['avg_turnover'])}", "",
                  "| Sub-period | Months | Beat the pool by (a year) | t |", "|---|---|---|---|"]
        lines += [f"| {k} | {v['months']} | {pct(v['excess_per_year'], True)} | {v['t']:+.2f} |"
                  for k, v in s["sub_periods"].items()]
        lines += ["", "| Year | Picks | Pool | SPY |", "|---|---|---|---|"]
        lines += [f"| {y} | {pct(r['net'])} | {pct(r['pool'])} | {pct(r['spy'])} |"
                  for y, r in s["by_year"].items()]
        last = max(s["by_year"])
        n_last = sum(1 for d in pd.read_csv(out / f"monthly_{version}.csv")["date"] if d.startswith(str(last)))
        lines += ["", f"Years group the monthly portfolios by the month they were bought, so each row "
                  f"compounds that year's monthly holdings. {last} has only {n_last} months, so it's "
                  f"left out of the 25% count."]
        b = base[version]
        lines += ["", f"Over the next 12 months, a pick beat SPY {pct(b['picks']['beat_spy'])} of the time "
                  f"and made 25%+ {pct(b['picks']['made_25pct'])} of the time (n = {b['picks']['n']:,}). "
                  f"Any pool stock: {pct(b['pool']['beat_spy'])} and {pct(b['pool']['made_25pct'])} "
                  f"(n = {b['pool']['n']:,}). These are base rates for the forecasters to beat; the "
                  f"12-month windows overlap, so they describe, not test."]
    lines += ["", "## Known limits (read before quoting any number above)", "",
              "- **Survivorship:** member-months without prices are mostly companies that were bought "
              "out or failed. They are left out, not guessed, and the table above counts them. Their "
              "effect on the result could go either way (buyouts usually pay a premium; failures lose).",
              "- **Large caps only, 2011 onward:** machine-readable SEC filings start around 2010, and "
              "the universe is the S&P 500. Small and mid caps, where growth and value effects are "
              "said to be strongest, aren't tested.",
              "- **Yahoo's adjusted prices** are imperfect around spinoffs.",
              "- **Banks and insurers** often lack operating income in their filings, so they rarely "
              "pass either screen (they stay in the pool).",
              "- **One trial each.** Every rule change is a new trial and is recorded; with many trials, "
              "a t of 2 is expected by luck, which is why the bar is 3."]
    out.mkdir(parents=True, exist_ok=True)
    text = "\n".join(lines) + "\n"
    (out / "report.md").write_text(text, encoding="utf-8")
    return text


EVIDENCE = {"growth-v1": ("growth-hunter", "Growth Hunter", "Growth Screen"),
            "value-v1": ("quality-value", "Quality & Value", "Value Screen")}


def write_evidence(results: dict, base: dict, cov: dict, out: Path) -> None:
    """Refresh the code-written evidence files in the agents' memory boxes."""
    src = out.relative_to(ROOT).as_posix()
    head = lambda agent_id: (f"---\nid: {agent_id}\nkind: agent-evidence\neditable_by: code\n"   # noqa: E731
                             f"updated: {date.today().isoformat()}\nsource: {src}/summary.json\n---\n\n")
    for version, (agent_id, name, twin) in EVIDENCE.items():
        s, b, a = results[version], base[version], results[version]["factor_adjusted"] or {}
        verdict = ("**passed** Stage A" if s["stage_a"] == "pass" else
                   "**did not pass** Stage A (factor-adjusted alpha against the pool with t ≥ 3, "
                   "holding up in most sub-periods)")
        text = head(agent_id) + f"""# Evidence for the {name}

## Your twin: the {twin} ({version})

The rule version of your method (`backend/analysis/screens.py`), backtested on S&P 500
members month by month from {s['start']} to {s['end']} ({s['months']} months), using SEC
numbers only after they were filed, after a {screens.COST_BPS:.0f} bp trading cost. It {verdict}.

- Against its Candidate Pool (every usable member that month): {pct(s['excess_per_year'], True)}
  a year, t = {s['excess_t']:+.2f}. After the known factor tilts: {pct(a.get('alpha_per_year'), True)}
  a year, t = {a.get('alpha_t', float('nan')):+.2f}.
- Yearly growth after costs: picks {pct(s['cagr_picks_net'])}, pool {pct(s['cagr_pool'])},
  SPY {pct(s['cagr_spy'])}. Years at or above 25%: {s['years_at_25pct']} of {s['years']}.
- About {s['avg_picks']:.0f} stocks passed in a typical month, out of about {s['avg_pool']:.0f}.

## Base rates for your probabilities (12 months ahead)

- A {twin} pick beat SPY {pct(b['picks']['beat_spy'])} of the time and made 25%+
  {pct(b['picks']['made_25pct'])} of the time (n = {b['picks']['n']:,} stock-months).
- Any usable S&P 500 member: {pct(b['pool']['beat_spy'])} and {pct(b['pool']['made_25pct'])}
  (n = {b['pool']['n']:,}).

Start `p_beat_market` and `p_hurdle` from these, and move away only as far as your
evidence justifies. The 12-month windows overlap, so treat them as descriptions, not proof.

## Limits

{pct(cov['usable_share'])} of member-months were usable. Most gaps are companies that were
bought out or failed and no longer trade, so their prices aren't available free. Large
caps only, from 2011. Full report: `{src}/report.md`.
"""
        (ROOT / "context" / "agents" / agent_id / "evidence.md").write_text(text, encoding="utf-8")
    pool = base["growth-v1"]["pool"]
    (ROOT / "context" / "agents" / "_shared" / "evidence.md").write_text(head("_shared") + f"""# Evidence for every agent

## Base rates: S&P 500 members, 12 months ahead

From {results['growth-v1']['start']} to {results['growth-v1']['end']}, a usable S&P 500
member beat SPY over the next 12 months {pct(pool['beat_spy'])} of the time and returned
25% or more {pct(pool['made_25pct'])} of the time (n = {pool['n']:,} stock-months; the
windows overlap). A forecaster that always says these numbers is the Base-Rate
Forecaster (charters §13). Beating it is the minimum.

Source: `{src}/summary.json`.
""", encoding="utf-8")


def run(record: bool = True) -> None:
    panel = pd.read_pickle(PANEL)
    cov = pit_data.coverage(panel)
    usable = panel[panel["missing"] == ""]
    cov["rows_with_guarded_ratio"] = int((screens.add_ratios(usable)["data_guarded"] > 0).sum())
    cov["market_value_from_cover_count"] = int((usable.get("mcap_shares") == "cover").sum())
    out = ROOT / "context" / "research" / "backtests" / f"{date.today().isoformat()}-screens-v1"
    out.mkdir(parents=True, exist_ok=True)
    results, base = {}, {}
    for version in screens.RULES:
        m = screens.monthly_returns(panel, version)
        m.to_csv(out / f"monthly_{version}.csv", index=False)
        s = screens.summarize(m)
        results[version], base[version] = s, screens.pick_base_rates(panel, m)
        if record:
            db.init()
            db.record_backtest_trial({
                "label": f"screen:{version} (ic_t_stat = excess-vs-pool t; ls_mean_net = monthly excess)",
                "universe": "sp500-pit+sec", "n_tickers": int(panel["cik"].nunique()),
                "lookback_years": 0, "fwd_days": 21, "cost_bps": screens.COST_BPS,
                "n_observations": int((panel["missing"] == "").sum()), "n_months": s["months"],
                "date_start": s["start"], "date_end": s["end"], "ic_mean": None,
                "ic_t_stat": s["excess_t"], "ir_annualized": s["information_ratio"], "pooled_ic": None,
                "ls_mean_net": round(s["excess_per_year"] / 12, 6)})
    (out / "summary.json").write_text(json.dumps(
        {"coverage": cov, "results": results, "base_rates": base, "rules": screens.RULES,
         "cost_bps": screens.COST_BPS, "min_names": screens.MIN_NAMES}, indent=2), encoding="utf-8")
    print(report(cov, results, base, out))
    write_evidence(results, base, cov, out)
    print(f"Wrote {out} and the agents' evidence files")


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "run"
    if cmd == "build":
        build()
    elif cmd == "run":
        run(record="--no-record" not in sys.argv)
    else:
        raise SystemExit(__doc__)
