"""Educational glossary — every concept the app uses, explained in three registers.

Each entry answers three questions a student needs, in order:
  definition — what it is (one or two precise sentences)
  intuition  — why anyone computes it (plain English, no notation)
  limits     — what it is bad at (the register textbooks skip and the one
               that separates education from decoration)

Static content, no data dependencies. Served whole by /api/glossary and
rendered by the Learn tab with client-side search.
"""
from __future__ import annotations

from typing import Any

# Categories render in this order in the UI.
CATEGORIES: list[str] = [
    "Scoring & signals",
    "Statistics & risk",
    "Regimes & cycles",
    "Advanced math",
    "Valuation",
    "Backtesting honesty",
]

TERMS: list[dict[str, str]] = [
    # --- Scoring & signals -------------------------------------------------
    {
        "id": "quant-score",
        "term": "Quant Score",
        "category": "Scoring & signals",
        "appears_in": "Quant tab",
        "definition": "This app's composite: eight component scores, each mapped to [-100, +100], combined as a weighted sum (technical 25%, regime 20%, valuation 15%, sentiment 10%, statistics 10%, risk 10%, spectral 5%, topology 5%). Verdict bands: above +30 Buy, below -30 Reduce.",
        "intuition": "No single lens is trustworthy, so average several independent ones and let disagreements cancel. If a module fails, its weight is redistributed so a missing input never flips the sign.",
        "limits": "The weights are hand-set, not fitted — and this app's own backtest found the composite has no predictive edge on its 14-name universe (IR ≈ -0.38). Treat the score as a structured description of the evidence, not a forecast.",
    },
    {
        "id": "technical-indicators",
        "term": "Moving averages, RSI, MACD",
        "category": "Scoring & signals",
        "appears_in": "Overview tab",
        "definition": "Transforms of past prices: a moving average smooths the trend (price above the 200-day MA = uptrend); RSI measures the speed of recent gains vs losses on a 0-100 scale; MACD tracks the gap between a fast and a slow average.",
        "intuition": "They compress a noisy price chart into 'is it trending, and is the trend tired?' RSI above ~70 says the recent run was unusually one-sided; MACD turning down says the trend is losing speed.",
        "limits": "All are derived from the same past prices, so they are heavily correlated with each other — three indicators agreeing is not three independent confirmations. They describe what happened; whether it continues is exactly the part they cannot know.",
    },
    {
        "id": "momentum-vs-meanreversion",
        "term": "Momentum vs. mean reversion",
        "category": "Scoring & signals",
        "appears_in": "everywhere",
        "definition": "The two opposing hypotheses about returns: momentum says winners keep winning over 3-12 month windows; mean reversion says stretched moves snap back toward an average over days-to-weeks.",
        "intuition": "Both are documented in academic data — at different horizons. Trend-following exploits the first; 'overbought/oversold' logic exploits the second. Which regime you are in decides which tool works.",
        "limits": "Momentum crashes hard at turning points (2009, 2020), and mean reversion loses steadily in strong trends. Any signal blending both — like this app's — can have them cancel exactly when conviction matters most.",
    },
    {
        "id": "conflict-flags",
        "term": "Conflict flags",
        "category": "Scoring & signals",
        "appears_in": "Quant tab",
        "definition": "Named contradictions between components, surfaced instead of averaged away: e.g. strong technicals on a rich valuation, or a cheap stock everyone hates, or a buy signal inside a volatile regime.",
        "intuition": "A weighted average of +80 and -80 prints a bland 0, hiding that two lenses violently disagree. A PM wants to see the disagreement itself — it is often the most informative thing on the page.",
        "limits": "Flags are hand-written rules, so they only catch the contradictions someone anticipated. No flag does not mean no contradiction.",
    },
    {
        "id": "relative-strength",
        "term": "Relative strength vs. SPY",
        "category": "Scoring & signals",
        "appears_in": "Overview tab",
        "definition": "The stock's trailing return minus the S&P 500's over the same window. Positive = leading the market, negative = lagging it.",
        "intuition": "Beating the index is the bar that matters: anyone can own the whole market in one click, so a single stock is judged against that default, not against zero.",
        "limits": "A stock can 'lead' simply by being higher-beta in an up-market — relative strength conflates leadership with leverage. Compare like-for-like risk before crediting skill to the stock.",
    },
    # --- Statistics & risk -------------------------------------------------
    {
        "id": "sharpe",
        "term": "Sharpe ratio",
        "category": "Statistics & risk",
        "appears_in": "Overview · Risk tabs",
        "definition": "Average excess return divided by the standard deviation of returns, annualized. Roughly: reward per unit of total wiggle.",
        "intuition": "It penalizes a strategy for taking a rough road to its return. Two strategies both making 12%/yr are not equal if one did it with double the swings.",
        "limits": "It punishes upside volatility as much as downside, assumes roughly normal returns (real returns have fat tails), and is easily gamed by strategies that earn small steady gains while hiding rare catastrophic losses — selling insurance looks great on Sharpe until it doesn't.",
    },
    {
        "id": "sortino",
        "term": "Sortino ratio",
        "category": "Statistics & risk",
        "appears_in": "Quant tab (statistics component)",
        "definition": "Sharpe's sibling: excess return divided by the standard deviation of negative returns only.",
        "intuition": "Investors do not complain about upside surprises, so only count the downside wiggle as risk.",
        "limits": "With few losing days in the sample the denominator gets tiny and the ratio explodes — a short calm stretch can print an absurdly flattering Sortino. Same fat-tail blindness as Sharpe.",
    },
    {
        "id": "max-drawdown",
        "term": "Maximum drawdown",
        "category": "Statistics & risk",
        "appears_in": "What-If · Risk tabs",
        "definition": "The largest peak-to-trough percentage decline over the window — the worst outcome for someone who bought the exact top and measured at the exact bottom.",
        "intuition": "It is the emotional cost of an investment. A stock that ends up 120% but fell 33% along the way only paid out to holders who did not sell at the bottom — and most people sell at the bottom.",
        "limits": "It is one historical path, not a distribution: the future max drawdown is routinely deeper than the past one. Deep drawdowns also take years to show up in data, so young histories understate it badly.",
    },
    {
        "id": "volatility",
        "term": "Annualized volatility",
        "category": "Statistics & risk",
        "appears_in": "Risk · What-If tabs",
        "definition": "Standard deviation of daily returns scaled to a yearly figure (multiplied by √252). A 30% vol stock 'typically' moves about 1.9% a day.",
        "intuition": "The market's going rate for how bumpy the ride is. It is the denominator of most risk-adjusted metrics and the raw material of options pricing.",
        "limits": "Volatility clusters — calm periods understate what is coming, stressed periods overstate it. And it treats up-moves as risk. It measures the ride, not the odds of permanent loss.",
    },
    {
        "id": "var",
        "term": "Value at Risk (VaR)",
        "category": "Statistics & risk",
        "appears_in": "Risk tab",
        "definition": "A percentile of the loss distribution: '95% VaR of 2.3%' means on 95% of days the loss was smaller than 2.3%. Computed here both historically (from actual past days) and parametrically (from a fitted normal).",
        "intuition": "One number for 'how bad is a bad day, normally?' Useful for sizing: if a normal-bad day costs 2.3%, size positions so a normal-bad day is survivable.",
        "limits": "VaR says nothing about how bad the remaining 5% of days are — the exact days that destroy portfolios. It is a fence at the edge of the ordinary, not a measure of the extraordinary. Basel-era finance learned this expensively in 2008.",
    },
    {
        "id": "cvar",
        "term": "CVaR / expected shortfall",
        "category": "Statistics & risk",
        "appears_in": "Risk tab",
        "definition": "The average loss on the days beyond the VaR threshold — 'when it is worse than the 95th percentile, how bad is it on average?'",
        "intuition": "It answers the question VaR dodges. Two stocks with identical VaR can have very different tails; CVaR sees the difference.",
        "limits": "It is estimated from the handful of worst days in the sample — often fewer than 25 observations — so it is noisy, and it still cannot see a tail event worse than anything in the history.",
    },
    {
        "id": "garch",
        "term": "GARCH volatility forecast",
        "category": "Statistics & risk",
        "appears_in": "Risk tab",
        "definition": "A model where today's variance depends on yesterday's variance and yesterday's squared surprise — capturing the fact that volatility clusters. Used here to forecast near-term vol and draw the fan chart.",
        "intuition": "After a wild day, tomorrow is likelier to be wild; after weeks of calm, calm. GARCH turns that observed persistence into a forecast that decays back toward long-run average vol.",
        "limits": "It forecasts the size of moves, never their direction, and it reacts to volatility rather than anticipating it — the first day of a crisis always blindsides it. Parameters fitted on calm data understate stress dynamics.",
    },
    {
        "id": "kelly",
        "term": "Kelly criterion",
        "category": "Statistics & risk",
        "appears_in": "Risk tab",
        "definition": "The bet size that maximizes long-run compound growth: edge divided by variance, roughly. Betting more than Kelly lowers long-run growth even when the edge is real.",
        "intuition": "Sizing matters as much as being right. A great edge bet too big still ruins you, because a 50% loss needs a 100% gain to recover.",
        "limits": "It needs the true edge and variance as inputs — which nobody has, only noisy estimates — and full Kelly with estimated inputs routinely over-bets. Practitioners use half-Kelly or less. If the estimated edge is imaginary (see this app's backtest), Kelly happily sizes an imaginary edge.",
    },
    {
        "id": "beta",
        "term": "Beta",
        "category": "Statistics & risk",
        "appears_in": "Valuation tab (discount rate)",
        "definition": "The slope of the stock's returns regressed on the market's: beta 1.3 means the stock historically moved 1.3% for the market's 1%.",
        "intuition": "Separates market-driven movement from stock-specific movement. High-beta names amplify whatever the market does — in both directions.",
        "limits": "Beta is unstable over time, depends on the window used, and measures co-movement, not company risk — a stable business with a jumpy stock gets a high beta. CAPM's use of it to set discount rates is convention, not physics.",
    },
    {
        "id": "skew-kurtosis",
        "term": "Skew & kurtosis (fat tails)",
        "category": "Statistics & risk",
        "appears_in": "Overview · Quant tabs",
        "definition": "Third and fourth moments of the return distribution: skew measures asymmetry (negative = crashes bigger than rallies), kurtosis measures tail weight (above 3 = extreme days more common than a normal distribution allows).",
        "intuition": "The normal bell curve says a 5-sigma day happens once in 14,000 years; equities deliver several per decade. Skew and kurtosis are the first warning that Gaussian intuition will underprice disaster.",
        "limits": "Both are estimated dominated by a few extreme days, so they are themselves noisy — one 2020-March in the window transforms the numbers. They describe the sample's tails, not the true tail you have not seen yet.",
    },
    {
        "id": "z-score",
        "term": "Z-score",
        "category": "Statistics & risk",
        "appears_in": "Overview tab",
        "definition": "How many standard deviations the latest observation sits from its mean. A -2.5 z-score day is in the worst ~1% under normality.",
        "intuition": "A unit-free 'how unusual is this?' — comparable across stocks with different volatilities.",
        "limits": "Because returns are fat-tailed, big z-scores happen far more often than the normal-curve percentile suggests. A 3-sigma day is noteworthy, not impossible — do not treat the implied probability literally.",
    },
    # --- Regimes & cycles --------------------------------------------------
    {
        "id": "hmm-regime",
        "term": "Hidden Markov regime model",
        "category": "Regimes & cycles",
        "appears_in": "Quant tab",
        "definition": "A model assuming the market occupies one of a few unobserved states (here 4, over trend and volatility features), each generating returns from its own distribution, with estimated switching probabilities. The fitted model labels today Bull / Bear / Chop / Volatile with a confidence.",
        "intuition": "Markets behave differently in different moods, and the mood persists. If you can identify the current mood, every other signal can be read in context — a buy signal in a Volatile regime deserves a discount.",
        "limits": "The states are statistical clusters, not economic facts — the model will find 4 regimes even in pure noise, because it was told to find 4. Labels near a transition are unstable, and the fit sees the whole window, so historical regime labels look cleaner than they were in real time.",
    },
    {
        "id": "spectral",
        "term": "Spectral analysis (FFT periodogram)",
        "category": "Regimes & cycles",
        "appears_in": "Quant tab",
        "definition": "Decomposes the detrended price series into sine waves and reports which cycle lengths carry the most power; the phase of the dominant cycle says whether the series sits near a crest or trough.",
        "intuition": "If a stock genuinely oscillates on, say, a 3-week rhythm (earnings drift, flows, positioning), Fourier analysis will find it without being told where to look.",
        "limits": "Fourier assumes the cycle is stable in period and amplitude — market 'cycles' are neither. A periodogram of pure random-walk noise still has a biggest peak, so a dominant cycle is always 'found'. This is why the component gets only 5% weight.",
    },
    {
        "id": "wavelets",
        "term": "Wavelet decomposition",
        "category": "Regimes & cycles",
        "appears_in": "Quant tab",
        "definition": "Like Fourier analysis but localized in time: it shows which cycle lengths were active when, instead of averaging over the whole window.",
        "intuition": "A cycle that existed in 2024 but died in 2025 shows up honestly in a wavelet picture, where a plain FFT would smear it across the whole period.",
        "limits": "More honest about time-variation, but even more parameters to over-read. Attractive pictures of transient 'cycles' are easy to generate and easy to over-interpret.",
    },
    # --- Advanced math -----------------------------------------------------
    {
        "id": "tda",
        "term": "Topological data analysis (persistence)",
        "category": "Advanced math",
        "appears_in": "Quant tab",
        "definition": "Embeds the recent price series as a point cloud (delay embedding), then measures its shape: persistent loops in the cloud indicate cyclical structure; their strength is summarized in a persistence diagram.",
        "intuition": "A genuinely oscillating system traces a ring in delay coordinates; a trending or random one does not. TDA asks 'does the geometry of recent prices contain a loop?' without assuming any particular cycle length.",
        "limits": "Financial series are short and noisy by TDA standards, and the pipeline (embedding dimension, delay, threshold) has many knobs whose settings drive the answer. In this app it is an experiment carrying 5% weight — its backtested contribution has not justified more.",
    },
    {
        "id": "manifold",
        "term": "Manifold learning (UMAP / Isomap)",
        "category": "Advanced math",
        "appears_in": "Quant tab",
        "definition": "Nonlinear dimensionality reduction: windows of recent returns are treated as high-dimensional points and projected to 2-D while trying to preserve neighborhood structure, revealing clusters of similar market days.",
        "intuition": "If today's market 'looks like' a cluster of past days, those days' aftermaths are at least worth knowing. The 2-D map makes similarity visible.",
        "limits": "The axes of the projection mean nothing individually, distances between far-apart clusters are unreliable, and different random seeds redraw the map. It is an exploration tool that suggests hypotheses — it proves nothing, which is why it feeds no score.",
    },
    # --- Valuation ---------------------------------------------------------
    {
        "id": "dcf",
        "term": "Discounted cash flow (DCF)",
        "category": "Valuation",
        "appears_in": "Valuation tab",
        "definition": "Intrinsic value as the sum of forecast future free cash flows, each divided by (1 + discount rate)^years, plus a terminal value for everything beyond the forecast horizon.",
        "intuition": "A business is worth the cash it will hand its owners, discounted for the wait and the risk. Everything else — multiples, sentiment, momentum — is shorthand for this.",
        "limits": "Extremely sensitive to its assumptions: small changes in terminal growth or discount rate swing the answer by tens of percent (see the sensitivity matrix). This app clips growth assumptions at 15%/yr, so structural compounders will systematically screen as 'overvalued'. A DCF is a disciplined way to expose assumptions, not a machine that outputs truth.",
    },
    {
        "id": "discount-rate",
        "term": "Discount rate (CAPM)",
        "category": "Valuation",
        "appears_in": "Valuation tab",
        "definition": "The required annual return used to shrink future cash to present value; built here as risk-free rate + beta × equity risk premium.",
        "intuition": "A dollar promised in 2036 is worth less than a dollar today — more less if the promise is risky. The discount rate prices both the wait and the doubt.",
        "limits": "Every input is contestable: which risk-free rate, whose risk premium estimate, beta over which window. A 1-point change in the rate moves a long-duration valuation ~15-25%. The app uses static values — if Treasury yields have moved, so has every fair value here.",
    },
    {
        "id": "terminal-growth",
        "term": "Terminal growth",
        "category": "Valuation",
        "appears_in": "Valuation tab",
        "definition": "The constant growth rate assumed forever after the explicit forecast years; the terminal value it produces is usually 60-80% of the whole DCF.",
        "intuition": "You cannot forecast year-by-year forever, so after a few years you assume the company matures into a steady grower — typically at or below the economy's growth rate.",
        "limits": "The majority of the valuation rests on the least forecastable number in it. Nudge terminal growth from 2.0% to 3.0% and watch the sensitivity matrix — that one assumption often swings fair value more than every near-term forecast combined.",
    },
    {
        "id": "multiples",
        "term": "Multiples (P/E, P/S, EV/EBITDA)",
        "category": "Valuation",
        "appears_in": "Peers · Valuation tabs",
        "definition": "Price scaled by a fundamental: price/earnings, price/sales, and enterprise-value/EBITDA (which includes debt, so leverage does not distort the comparison).",
        "intuition": "What am I paying per dollar of what the business produces? Comparing that across similar companies is the fastest sanity check on any valuation.",
        "limits": "A multiple is only 'cheap' relative to comparable growth, margins, and risk — the peer table pairs them for exactly that reason. Earnings are accounting numbers, negative-earnings names have no meaningful P/E, and cross-industry comparisons are close to meaningless.",
    },
    {
        "id": "relative-value-score",
        "term": "Relative value score",
        "category": "Valuation",
        "appears_in": "Peers tab",
        "definition": "The stock's average percentile rank against its curated peer group across five fundamental metrics (P/E, P/S, EV/EBITDA, revenue growth, gross margin). 100 = best-in-group on everything. Momentum is displayed alongside but deliberately excluded from the score.",
        "intuition": "Ranks-within-a-peer-set neutralize industry effects: software multiples only make sense against software multiples.",
        "limits": "The peer groups are hand-curated and small, so one odd peer moves every percentile; yfinance gaps shrink the sample further (the score refuses to print with fewer than 3 valid metrics). Momentum was excluded after it was caught making hot stocks look 'cheap'.",
    },
    # --- Backtesting honesty ----------------------------------------------
    {
        "id": "backtest",
        "term": "Backtest (point-in-time)",
        "category": "Backtesting honesty",
        "appears_in": "score_backtest module",
        "definition": "Replaying a strategy on history using, at each simulated date, only information that existed by that date — then comparing the decisions against what followed.",
        "intuition": "The only honest way to ask 'would this signal have worked?' The discipline is the cutoff: at each date, slice the data, recompute everything from the slice, record the forward return, move on.",
        "limits": "Even a perfectly point-in-time backtest is still one draw of history, still in-sample if you tuned anything while looking at it, and still silent about costs, slippage, and capacity. Passing an honest backtest is necessary, nowhere near sufficient.",
    },
    {
        "id": "lookahead-bias",
        "term": "Lookahead bias",
        "category": "Backtesting honesty",
        "appears_in": "score_backtest module",
        "definition": "Any leak of future information into a simulated past decision — using today's revised fundamentals for a 2023 decision, a peer multiple computed from later prices, or news archives that did not exist then.",
        "intuition": "It is the most common way backtests lie, and the subtlest: the code runs, the numbers look great, and nothing flags that the strategy 'knew' things it could not have known. It is why this app's backtest excludes valuation and sentiment — the free data feed cannot supply them as-of a past date.",
        "limits": "Detecting it requires auditing data provenance line by line; no statistic in the output reveals it. When a backtest looks too good, lookahead is the first suspect, not genius.",
    },
    {
        "id": "survivorship-bias",
        "term": "Survivorship bias",
        "category": "Backtesting honesty",
        "appears_in": "every backtest here",
        "definition": "Testing on a universe selected today — which silently contains only companies that survived and prospered. The failures that a real investor could have picked are missing from the data.",
        "intuition": "Study only lottery winners and buying tickets looks brilliant. This app's 14-name watchlist of 2026 mega-caps is exactly such a set: every backtest on it inherits the bias, which is why none of its results are quotable as skill.",
        "limits": "Unfixable without point-in-time universe data including delisted names (CRSP-style). Free data feeds cannot provide it — the single biggest data limitation of this project.",
    },
    {
        "id": "information-coefficient",
        "term": "Information coefficient (IC)",
        "category": "Backtesting honesty",
        "appears_in": "score_backtest module",
        "definition": "The rank correlation between a signal's scores at a date and the subsequent returns across the same names. IC of +0.05 sustained across many periods is a respectable professional signal; 0 is no skill.",
        "intuition": "It asks the cross-sectional question that matters: did the signal order the names correctly? Not 'did the market go up' but 'did my favorites beat my least-favorites?'",
        "limits": "On a small correlated universe an IC is a rank correlation of a handful of points — this app's 3-ticker pilot printed IC +0.19 and the 14-ticker run printed -0.03, a swing that is pure sampling noise. Correlated names also shrink the effective sample far below the observation count.",
    },
    {
        "id": "information-ratio",
        "term": "Information ratio (IR)",
        "category": "Backtesting honesty",
        "appears_in": "score_backtest module",
        "definition": "Mean IC divided by the standard deviation of IC, annualized — consistency of skill, not just its average. IR above ~0.5 sustained is a strong professional result.",
        "intuition": "An average edge that whipsaws wildly period to period is hard to monetize; IR rewards signals that are modestly right reliably over ones that are occasionally spectacular.",
        "limits": "Estimating a standard deviation from 37 monthly ICs gives huge error bars — this app's IR swung from +0.05 to -0.38 when 4 names were added. Quoting an IR without its sample size is how backtests mislead.",
    },
    {
        "id": "hit-rate",
        "term": "Hit rate",
        "category": "Backtesting honesty",
        "appears_in": "score_backtest module",
        "definition": "The fraction of signals that ended profitable — long calls that rose, short calls that fell. 50% is a coin flip.",
        "intuition": "The most human-readable skill metric: how often was it right?",
        "limits": "It ignores magnitude — a 56% hit rate loses money if the misses are bigger than the hits — and in a rising market every long signal 'hits' regardless of skill. Always read it against the base rate: if 60% of all 21-day windows were up, a 56% long hit rate is below chance.",
    },
    {
        "id": "in-sample",
        "term": "In-sample vs. out-of-sample",
        "category": "Backtesting honesty",
        "appears_in": "every result here",
        "definition": "In-sample: evaluated on the same data used (formally or informally) to design the strategy. Out-of-sample: evaluated on data the design never saw — a held-out period, or the live future.",
        "intuition": "Any flexible strategy can be tuned until history looks great; the tuning is invisible in the final numbers. Only untouched data can distinguish a discovered edge from a memorized one. This app's weights are hand-set by someone who lived through the test window, so all its results are effectively in-sample.",
        "limits": "One out-of-sample pass is only honest once — peek at the held-out result, adjust, and re-run, and it has silently become in-sample too. Professionals guard the holdout like a lab seal.",
    },
    {
        "id": "vader",
        "term": "VADER sentiment",
        "category": "Backtesting honesty",
        "appears_in": "Sentiment tab",
        "definition": "A lexicon-based sentiment scorer: each word carries a hand-assigned valence, combined with rules for negation, intensity and punctuation, producing a compound score in [-1, +1] per headline.",
        "intuition": "Fast, free, deterministic, and needs no training — reasonable for a first pass over a stream of headlines.",
        "limits": "VADER was built for social media, not financial prose: 'shares plunge on beat-and-raise guidance' confuses it, negation across clauses escapes it, and headline sentiment is mostly already priced in by the time yfinance serves it. Fine as a display widget; thin as a signal — which is why it carries only 10% weight and sits out of the backtest.",
    },
]


def get_glossary() -> dict[str, Any]:
    """Full glossary payload for the Learn tab."""
    return {
        "categories": CATEGORIES,
        "terms": TERMS,
        "term_count": len(TERMS),
    }
